### ISSUE TITLE
Cannot play

### ISSUE THREAD

**Issue by francisco-navarro** [derhuerst/play-on-apple-tv#1]
I see this problem with apple tv 3:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected response to PTTH/1.0 Upgrade request
    at /Users/pakonat/.nvm/versions/node/v7.10.1/lib/node_modules/play-on-apple-tv/node_modules/reverse-http/index.js:59:32
    at /Users/pakonat/.nvm/versions/node/v7.10.1/lib/node_modules/play-on-apple-tv/node_modules/consume-http-header/index.js:12:5
    at done (/Users/pakonat/.nvm/versions/node/v7.10.1/lib/node_modules/play-on-apple-tv/node_modules/consume-until/index.js:52:5)
    at Socket.consume (/Users/pakonat/.nvm/versions/node/v7.10.1/lib/node_modules/play-on-apple-tv/node_modules/consume-until/index.js:33:7)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:188:7)
    at emitReadable_ (_stream_readable.js:434:10)
    at emitReadable (_stream_readable.js:428:7)
    at readableAddChunk (_stream_readable.js:189:13)
```

**Comment by derhuerst** [comment]
Did you confirm that your apple tv otherwise works fine? Do you have an iOS/macOS device to test with?

**Comment by francisco-navarro** [comment]
Yes, I have two iPhone and two macbook with sierra, and all play perfectly.

**Comment by derhuerst** [comment]
I really don't know what the reason might be. I would *assume* the AirPlay protocol implementations haven't changed between the versions of the Apple TV 3 firmwares.

Just to rule out another source of errors: Could you try with Node stable? [Node 7 is basically dead.](https://github.com/nodejs/Release#release-schedule)

**Comment by derhuerst** [comment]
Please reopen once you have tried with Node `>= 8`. (I'm aware that there might really be a bug in `play-on-apple-tv`, but keeping an overview over many issues is hard if half of them are stale.)

**Comment by derhuerst** [comment]
ping @francisco-navarro. Do you have additional information?
