### ISSUE TITLE
support the PIN code of recent Apple TVs

### ISSUE THREAD

**Issue by francisco-navarro** [derhuerst/play-on-apple-tv#2]
When I try to connect, I can't authenticate:

The error is: 

```
Error: Unexpected response from Apple TV: 403
at ClientRequest.<anonymous> (~/airplayer/node_modules/airplay-protocol/index.js:155:43)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
```

**Comment by derhuerst** [comment]
As in #1, what is your environment? OS, Node version, dependencies up to date?

edit: Apple TV model and firmware version?

**Comment by francisco-navarro** [comment]
I find the problem is the authentication with TV OS 10.2
I use node v8.4.0 (npm v5.3.0), and Apple TV4. It needs a PIN to authenticate. I'm working in another solution using this: https://github.com/funtax/AirPlayAuth but after authenticate I cannot play.
 I will continue to work with this. I'm sending correct petitions and using this protocol specification: https://nto.github.io/AirPlay.html

**Comment by derhuerst** [comment]
also related: https://github.com/watson/airplay-protocol/issues/7

**Comment by derhuerst** [comment]
This library can probably be used. https://github.com/edc1591/node-appletv

PRs welcome!

**Comment by francisco-navarro** [comment]
I'll investigate, thank you.
